### ISSUE TITLE
apply_changes doesn't find __linting_system deep in the tree

### ISSUE THREAD

**Issue by vonschultz** [thundergolfer/bazel-linting-system#12]
The linting system produces directories called `__linting_system` under the `bazel-genfiles` directory, sometimes several directories deep, if the project under analysis has Bazel subpackages. Then `apply_changes` tries to find them using
```
	lintSysPkgRootPattern := genfilesRoot + "/**/__linting_system"
	matches, err := filepath.Glob(lintSysPkgRootPattern)
```
The problem is that `filepath.Glob` does not support `**` in the pattern string. (See also https://golang.org/pkg/path/filepath/#Glob and https://golang.org/pkg/path/filepath/#Match — there's only `*` which matches "non-Separator characters". There's also https://stackoverflow.com/questions/26809484/how-to-use-double-star-glob-in-go)

The effect becomes that no changes get applied for our nested subpackages.

Version: Current master, 7701c83f68.
Expected behavior: Changes are applied from all the `__linting_system` directories in `bazel-genfiles`.
Actual behavior: Changes from subpackages are skipped.

**Comment by thundergolfer** [comment]
Thanks for the issue report.
