### ISSUE TITLE
License information is missing

### ISSUE THREAD

**Issue by vonschultz** [thundergolfer/bazel-linting-system#13]
There is no license information in the repository that I can find. If it's meant to be proprietary, I suppose that isn't actually needed, but then it's nice to have some "All rights reserved" comments in the code so it's clear that's the intention. If it's meant to be open source, a license needs to be chosen. See e.g. https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

The Apache 2.0 license seems to be quite popular among Bazel people, if you're open for a suggestion.

**Comment by thundergolfer** [comment]
Thanks for creating the issue, and thanks for the email. 

I agree with following the common choice in the ecosystem. I'll add that license so that you can do your evaluation 👍

**Comment by thundergolfer** [comment]
Done 🙂
